# Application Configuration
spring:
  application:
    name: ServiceRegistry

# Server Configuration
server:
  port: 8761

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
